settings:
  username: "SaptajitSaha"
  commit_msg: "⚡ Update GitHub activity feed"
  max_lines: 6
  readme_file: "./README.md"
  disabled_events:
    - "comments"
  url_text: "{REPO}{ID}"
  date:
    timezone: "GMT+05:30"
    text: "Last updated: {DATE}"
    format: "dddd, mmmm dS, yyyy, h:MM:ss TT"
  commit_name: "github-actions[bot]"
  commit_email: "41898282+github-actions[bot]@users.noreply.github.com"
  line_prefix: "│ {NUM}. "

messages:
  PushEvent: "⬆️ Pushed {AMOUNT} commit(s) to {REPO}"
  IssuesEvent:
    opened: "🟠 Opened issue {ID} in {REPO}"
    closed: "✔️ Closed issue {ID} in {REPO}"
  PullRequestEvent:
    opened: "🔀 Opened PR {ID} in {REPO}"
    closed: "❌ Closed PR {ID} in {REPO}"
    merged: "🚀 Merged PR {ID} in {REPO}"
  CreateEvent: "📦 Created {REPO}"
  ForkEvent: "🍴 Forked {FORK} from {REPO}"
  GollumEvent: "📖 Updated wiki in {REPO}"
  MemberEvent: "🤝 Became collaborator on {REPO}"
  PullRequestReviewEvent: "📝 Reviewed PR {ID} in {REPO}"
  ReleaseEvent: "🏷️ Released {ID} in {REPO}"
  WatchEvent: "⭐ Starred {REPO}"
